cats/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'cat'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('create/', views.PostCreateView.as_view(), name='create_post'),
    path('categories/', views.categories, name='categories')
]

meow/urls.py
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy
from django.views.generic.edit import CreateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('pages:home')
        ),
        name='registration'
    ),
    path('', include('pages.urls', namespace='pages')),
    path('cats/', include('cats.urls', namespace='cat')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home_page, name='home')
]

cats/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Category(models.Model):
    is_published = models.BooleanField(default=True)
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=255)
    slug = models.SlugField(
        'Идентификатор',
        unique=True,
        help_text='Идентификатор страницы для URL; разрешены символы '
                  'латиницы, цифры, дефис и подчёркивание.'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Location(models.Model):
    name = models.CharField(
        'Название места',
        max_length=256,
    )
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'местоположение'
        verbose_name_plural = 'Местоположения'


class Post(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    video = models.FileField(upload_to='videos/', blank=True, null=True)
    is_published = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now=True)
    date_update = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор публикации',
        null=True
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Местоположение'
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Категория',
        related_name='category_post'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

pages/models.py
from django.db import models

# Create your models here.

cats/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Post

User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

cats/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy, reverse
from django.shortcuts import render

from .forms import PostForm
from .models import Category, Post


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'cats/create.html'

    def get_success_url(self):
        return reverse(
            'cat:home'
        )


def categories(request):
    categories = Category.objects.filter(
        is_published=True
    ).order_by('title')
    context = {'categories': categories}
    return render(request, 'cats/categories.html', context)

pages/views.py
from random import choice

from django.shortcuts import render

from cats.models import Post


def home_page(request):
    random_post = choice(Post.objects.all())
    context = {'post': random_post}
    return render(request, 'cats/cats.html', context)

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    {% include "includes/header.html" %}
    <main>
        {% block content %}{% endblock %}
    </main>
    {% include "includes/footer.html" %}
</body>
</html>

templates/cats/categories.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% for category in categories %}
  {{ category.title }} <br>
{% endfor %}
{% endblock %}

templates/cats/cats.html
{% extends "base.html" %}
{% load static %}

{% block title %} Welcome to cats gallery {% endblock %}

{% block content %}
<div class="box">
    {{ post.title }} <br>
    {% if post.image %}
    <img src="{{ post.image }}" width="600px">   <br>
    {% endif %}
    {% if post.video %}
        <video src="{{ post.video }}" controls width="600px"></video> <br>
    {% endif %}
    {{ post.date }} <br>
    {{ post.author }} <br>
    {{ post.location }} <br>
    {{ post.category }} <br>
</div>
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/home_page.css' %}">
{% endblock %}

templates/cats/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %} Создание поста {% endblock %}

{% block content %}
  {% csrf_token %}
<div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
            {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
{% endblock %}

templates/includes/footer.html
{% load static %}

<div class="footer">
  <img src="{% static 'img/lapka.jpg' %}" alt="Footer Image">
  <div class="footer-blocks">
    <div class="footer-block">
      <h3>Условия использования</h3>
      <p>Insert your terms of use here.</p>
    </div>
    <div class="footer-block">
      <h3>Контакты автора</h3>
      <p>Email: author@example.com<br>Phone: +1 234 567 890</p>
    </div>
    <div class="footer-block">
      <h3>Политика конфиденциальности</h3>
      <p>Insert your privacy policy here.</p>
    </div>
  </div>
</div>

templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    {% with request.resolver_match.view_name as view_name %}
    <div class="container-fluid" style="justify-content: space-between;">
      <a class="navbar-brand" href="{% url 'pages:home' %}"><img src="{% static 'img/logo.png' %}" alt="logo" width="100px"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active fs-2" aria-current="page" href="#">Лента</a>
          <a class="nav-link fs-2" href="{% url 'cat:categories' %}">Категории</a>
          <a class="nav-link fs-2" href="#">Благотворительность</a>
        </div>
      </div>
    </div>
    {% if user.is_authenticated %}
    <div class="btn-group" role="group" aria-label="Basic outlined example">
      <a class="nav-link fs-2" href="{% url 'cat:create_post' %}">Написать пост</a>
      <a class="nav-link fs-2" href="#">{{ user.username }}</a>
      <a class="nav-link fs-2" href="{% url 'logout' %}">Выйти</a>
    </div>
    {% else %}
    <div class="btn-group" role="group" aria-label="Basic outlined example">
      <a class="nav-link fs-2" href="{% url 'login' %}">Войти</a>
      <a class="nav-link fs-2" href="{% url 'registration' %}">Регистрация</a>
    </div>
    {% endif %}
    {% endwith %}
  </nav>
</header>